### ISSUE TITLE
Recipes Assignment

### ISSUE THREAD

**Issue by gwrightsimmons** [IntroToCode/Spring21_Recipes_Codemates11#1]
## 💬 Discussion topic

Assignment requirements 

## ❗ Potential issues

Finding time to sync/ finish this project; making sure we all contribute

## 👥 People to consult

Codemates 11

## 📃 Details

**Criteria for grading:** 

**Your Codemates team used Issues to clearly delineate work (30%)**
- Was there stated acceptance criteria?
- Were ideas communicated, debated, and resolved in the Pull Requests?
- Have related issues been closed when resolved?

**Your Codemates team used Pull Requests to discuss solutions (60%)**
- Did every team member commit to the Pull Requests? (comments are not commits)
- Did the team use the reviews feature of GitHub to get explicit approval? 
- Did at least TWO people approve each Pull Request? 

**Work collaboratively on changes until objective is completed (10%)**
- Are there (3) fully completed recipes on the main/master branch?
- Was there conversation, disagreement, discussion of style in the Pull Requests?

**Comment by gwrightsimmons** [comment]
Flagging that we need to make sure we have acceptance criteria for all our recipes. No half-baked recipes :)

**Comment by cailintodd** [comment]
Agree with @gwrightsimmons -recipes where you actually cook is what is acceptable.

**Comment by cailintodd** [comment]
We are working as a team! Yahoo!
