### ISSUE TITLE
Breakfast Recipe Decision

### ISSUE THREAD

**Issue by cailintodd** [IntroToCode/Spring21_Recipes_Codemates11#2]
## 💬 Discussion topic
What will the recipe for smoothies be? 

## ❗ Potential issues

Why type of smoothie to make? Fruit, vegetable-based or both? 

## 👥 People to consult

Georgia, Felipe, Tai, Cailin and Ali 

## 📃 Details

Banana Smoothie (FC's suggestion): 
2 cups frozen sliced bananas
1/2 cup nonfat plain Greek yogurt
1/2 tablespoon ground flax seeds
1 cup unsweetened plain almond milk
1 teaspoon vanilla extract

**Comment by cailintodd** [comment]
Other section forgotten: Place all ingredients in a high-speed blender and blend on high until smooth. Option to add more almond milk as needed.

**Comment by fcovarr1** [comment]
What if we replace nonfat plain Greek yogurt with a plant-based one from Oatly?

**Comment by gwrightsimmons** [comment]
Do we have serving size/ number of servings for this?

**Comment by Aloha15** [comment]
Should we add a suggestion to clean the blender right away after the smoothie is done? (It will be much harder to clean if you let it sit a while)

**Comment by cailintodd** [comment]
Decision resolved.
