### ISSUE TITLE
Lunch recipe decision 

### ISSUE THREAD

**Issue by tai-wu** [IntroToCode/Spring21_Recipes_Codemates11#3]
## 💬 Discussion topic

What will the recipe for rib fried rice for lunch be? 

## ❗ Potential issues

What type of meat, vegetables, and rice should we use? 

## 👥 People to consult

Georgia, Felipe, Cailin, Ali

## 📃 Details

Ingredients

2 tablespoons soy sauce
1 tablespoon sesame oil
2 tablespoons mirin
1 tablespoon rice vinegar
2 tablespoons hoisin
1 tablespoon gochujang
1/4 cup vegetable oil, divided
2 eggs, whisked
Kosher salt
1 medium red onion, diced
2 tablespoons minced ginger
2 cloves garlic, minced
2 carrots, peeled and finely diced
1½ cups leftover Barbecue Pork Ribs, cubed (recipe linked above)
4 cups cooked, day-old short grain rice
1 cup frozen peas, thawed
1/2 cup sliced scallions

Preparation

1. In a small bowl, combine the soy sauce, sesame oil, mirin, rice vinegar, hoisin and gochujang until well combined.

2. In a large nonstick skillet or wok, heat 1 tablespoon vegetable oil over medium heat. Season eggs with kosher salt, to taste. Once the oil is hot, add in the eggs. Cook, folding and stirring constantly, until fully scrambled. Break into small pieces with a spatula and transfer to a small plate.

3. Wipe out the skillet or wok and heat over medium-high heat. Add the remainder of the vegetable oil, followed by the red onion, ginger and garlic. Cook for 2 minutes.

4. Add the carrots and cook for another 2 minutes.

5. Once the carrots are just tender, add in the pork and reserved sauce. Cook for 30 seconds before adding the short grain rice.

6. Sauté the rice for another minute, then add in the peas, scrambled eggs and sliced scallions. Once the peas are heated through, remove from heat and serve.

**Comment by cailintodd** [comment]
@tai-wu-is there a BBQ recipe for the pork ribs? There is a note above?

**Comment by tai-wu** [comment]
@cailintodd, good catch. Will need to add a BBQ pork ribs recipe as an issue.

**Comment by cailintodd** [comment]
We are aligned regarding this recipe.
