### ISSUE TITLE
Recipe Acceptance Criteria

### ISSUE THREAD

**Issue by gwrightsimmons** [IntroToCode/Spring21_Recipes_Codemates11#4]
## 💬 Discussion topic

What constitutes a completed recipe?

## ❗ Potential issues

??

## 👥 People to consult

Codemates11

## 📃 Details

- Ingredients List
- Gear list (e.g., for smoothie, need a blender)
- Serving size
- Number of servings
- Steps to complete
- Estimated prep time
- Estimated cook time

**Comment by cailintodd** [comment]
We are aligned regarding recipe criteria.
