### ISSUE TITLE
Dinner Recipe Decision 

### ISSUE THREAD

**Issue by cailintodd** [IntroToCode/Spring21_Recipes_Codemates11#5]
## 💬 Discussion topic
What will our dinner recipe be? 

## ❗ Potential issues

Does everyone like chicken? 

## 👥 People to consult

Team 11 

## 📃 Details
11⁄2 pounds (680 grams) small potatoes, scrubbed and halved if large

1⁄2 pound (226 grams) white mushrooms, wiped clean, trimmed and cut in half if large

1 large shallot or medium onion, cut into 8 wedges, rinsed and patted dry

4 garlic cloves, unpeeled

8 sprigs fresh rosemary

8 sprigs fresh thyme

Fine sea salt and freshly ground pepper

6 tablespoons (90 ml) extra-virgin olive oil 4 tablespoons balsamic vinegar

4 whole chicken legs (thigh and drumstick), patted dry (see headnote)

Center a rack in the oven and preheat it to 450 degrees F. Rub a baking sheet with a little oil (or line it with foil and oil the foil).

Put the potatoes, mushrooms, shallot or onion and garlic in a large bowl. Toss in 4 sprigs each of the rosemary and thyme, 1 teaspoon salt, a few grindings of pep- per, 3 tablespoons of the oil and 3 tablespoons of the balsamic. Mix everything well and spread the ingredients out on the baking sheet.

Put the chicken in the bowl, along with the remain- ing 3 tablespoons oil and 2 tablespoons balsamic,
1⁄2 teaspoon salt and a good amount of pepper, and mix well to coat the chicken. Move the vegetables around to make room for the chicken. Tuck the remaining herbs under each piece.

Roast the chicken for 40 minutes to 1 hour, until a thermometer stuck into the thickest part of a thigh measures 165 degrees F.

Serve everything on the baking sheet or a big platter; pour over the cooking juices.

**Comment by Aloha15** [comment]
Looks good! Just noticed that the first measurement is 11/2 (instead of 1/2, which I'm assuming is what it should be?)

**Comment by cailintodd** [comment]
@Aloha15 - yep, it should be 1.5. I think it comes up on the actual pull request. Great catch!

**Comment by cailintodd** [comment]
We are aligned regarding recipes and making changes via pull requests.
